// // import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Navbar from "@/components/Navebar";
// import { ThemeProvider } from "@/components/theme-provider";
// import { Metadata } from "next/dist/lib/metadata/types/metadata-interface";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
      
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <ThemeProvider
//           attribute="class"
//           defaultTheme="system"
//           enableSystem
//           disableTransitionOnChange
//         >
//         <Navbar/>
//         {children}
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }


import { ThemeProvider } from "@/components/theme-provider";
import "@/app/globals.css";
import Navbar from "@/components/Navebar";
import Footer from "@/components/Footer";
// import { BackgroundBeams } from "@/components/ui/background-beams";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar/>
          {children}
          <Footer/>
        </ThemeProvider>
        {/* <BackgroundBeams/> */}
      </body>
    </html>
  );
}